/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefundRefundTokenRouteImport } from './routes/refund.$refundToken'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRefundTokenRoute = RefundRefundTokenRouteImport.update({
  id: '/refund/$refundToken',
  path: '/refund/$refundToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/tickets': typeof TicketsRoute
  '/refund/$refundToken': typeof RefundRefundTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/tickets': typeof TicketsRoute
  '/refund/$refundToken': typeof RefundRefundTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/tickets': typeof TicketsRoute
  '/refund/$refundToken': typeof RefundRefundTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/merchandise'
    | '/tickets'
    | '/refund/$refundToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/merchandise' | '/tickets' | '/refund/$refundToken'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/merchandise'
    | '/tickets'
    | '/refund/$refundToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MerchandiseRoute: typeof MerchandiseRoute
  TicketsRoute: typeof TicketsRoute
  RefundRefundTokenRoute: typeof RefundRefundTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund/$refundToken': {
      id: '/refund/$refundToken'
      path: '/refund/$refundToken'
      fullPath: '/refund/$refundToken'
      preLoaderRoute: typeof RefundRefundTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  MerchandiseRoute: MerchandiseRoute,
  TicketsRoute: TicketsRoute,
  RefundRefundTokenRoute: RefundRefundTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
