/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/ticket': typeof TicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/ticket': typeof TicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/merchandise': typeof MerchandiseRoute
  '/ticket': typeof TicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/merchandise' | '/ticket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/merchandise' | '/ticket'
  id: '__root__' | '/' | '/analytics' | '/merchandise' | '/ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MerchandiseRoute: typeof MerchandiseRoute
  TicketRoute: typeof TicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  MerchandiseRoute: MerchandiseRoute,
  TicketRoute: TicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
